name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.target') }}

    - name: Build with Maven
      run: mvn verify
      working-directory: edelta.example.migration.personlist.parent

    - name: Archive Test Results
      uses: actions/upload-artifact@v4
      if: ${{ failure() || cancelled() }}
      with:
        name: test-results-${{ runner.os }}
        path: '**/*.tests/target/surefire-reports'
